cmake_minimum_required(VERSION 3.22.1)
project(pcm_ring_test LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(Threads REQUIRED)
enable_testing()
add_executable(pcm_ring_test pcm_ring_test.cpp)
target_include_directories(pcm_ring_test PRIVATE ../../main/cpp)
target_link_libraries(pcm_ring_test PRIVATE Threads::Threads)
add_test(NAME pcm_ring COMMAND pcm_ring_test)
